package report

import (
	"fmt"
	"os"
	"time"
)

func Save(content, outputFile string) error {
	header := fmt.Sprintf("# Recon Notes\n_Generated by 0xchosen on %s_\n\n---\n\n",
		time.Now().Format("2006-01-02 15:04:05"))

	return os.WriteFile(outputFile, []byte(header+content), 0644)
}
